services:
  micronaut-consul:
    image: hashicorp/consul:latest
    container_name: micronaut-consul
    restart: always
    ports:
      - "8500:8500"   # Consul UI and API
      - "8600:8600/udp" # DNS Interface
    networks:
      - micronaut_net
    volumes:
      - micronaut-consul-data:/consul/data
    command: agent -server -bootstrap -node=micronaut-consul -client=0.0.0.0 -ui -bind=0.0.0.0
    environment:
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'

networks:
  micronaut_net:
    external: true
    
volumes:
  micronaut-consul-data:
