services:
  customer-app:
    image: product-backup-api:latest
    container_name: product-backup-api
    environment:
      - MYSQL_HOST=micronaut_mariadb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=admin
      - CONSUL_HOST=micronaut-consul
      - CONSUL_PORT=8500
      - SERVICE_ADDRESS_NAME=product-backup-api
    ports:
      - "8083:8083"
    networks:
      - micronaut_net

networks:
  micronaut_net:
    external: true
